### ISSUE TITLE
[AVM Module Issue]: Idempotency issue when setting management_group_hierarchy_settings

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/terraform-azurerm-avm-ptn-alz#115]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

v0.9.0-beta

### Description

When setting `management_group_hierarchy_settings`, `default_management_group_name` looks to be causing an idempotency issue as the module is adding the provider prefix, but the API is returning the name on its own, without the prefix. This causes an update to be triggered every time.

```
management_group_hierarchy_settings = {
    default_management_group_name            = var.default_management_group_name #Set to global-default
    require_authorization_for_group_creation = true
    update_existing                          = true
  }
```

https://github.com/Azure/terraform-azurerm-avm-ptn-alz/blob/ef8128257d4e646a46f81784aaf9c7941092be15/main.hierarchy_settings.tf#L30

```HCL
# module.alz.module.alz_global.azapi_update_resource.hierarchy_settings[0] will be updated in-place
  ~ resource "azapi_update_resource" "hierarchy_settings" {
      ~ body                    = {
          ~ properties = {
              ~ defaultManagementGroup               = "global-default" -> "/providers/Microsoft.Management/managementGroups/global-default"
                # (1 unchanged attribute hidden)
            }
        }
        id                      = "/providers/Microsoft.Management/managementGroups/######/settings/default"
        name                    = "default"
      ~ output                  = {} -> (known after apply)
        # (5 unchanged attributes hidden)
```

**Comment by matt-FFFFFF** [comment]
Thanks! Will update in the next version
