### ISSUE TITLE
Bug: Display Name property missing from policy assignments

### ISSUE THREAD

**Issue by OmnipotentOwl** [Azure/terraform-azurerm-avm-ptn-alz#12]
## Summary
After deploying the alz module and reviewing the deployment for policy remediations I noticed the following effect in the Azure Portal around navigating the policy assignments and the policy set definition references whereby the lack of a display name property on the Policy Assignment causes the Azure Portal to render the breadcrumb navigation is a strange way. I have included a picture below of an example of this behavior.

![image](https://github.com/Azure/terraform-azurerm-avm-ptn-alz/assets/1769881/7b2cd48c-e4be-4834-b089-57768f72951f)

Looking through the code it looks like in the `azurerm_management_group_policy_assignment` resource block the displayName property is not being pulled forward from the processed assignments from the provider
```hcl
resource "azurerm_management_group_policy_assignment" "this" {
  for_each = local.alz_policy_assignments_decoded

  name                 = each.key
  management_group_id  = azurerm_management_group.this.id
  policy_definition_id = each.value.properties.policyDefinitionId
  description          = try(each.value.properties.description, "")
  enforce              = try(each.value.properties.enforce, "Default") == "Default" ? true : false
  metadata             = jsonencode(try(each.value.properties.metadata, {}))
  parameters           = try(each.value.properties.parameters, null) != null && try(each.value.properties.parameters, {}) != {} ? jsonencode(each.value.properties.parameters) : null
  location             = try(each.value.location, null)
```

From this it looks like just adding in the displayName in the format of `try(each.value.properties.displayName, "")` would resolve this issue and not cause this behavior in the Azure Portal. I can go ahead and submit a PR for this if that helps.

**Comment by jaredfholgate** [comment]
Will be released shortly.
