### ISSUE TITLE
[AVM Module Issue]: Unable to set selectors for overrides in policy_assignments_to_modify

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/terraform-azurerm-avm-ptn-alz#132]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

v0.9.0-beta2

### Description

There is a mismatch between the `policy_assignments_to_modify` variable definition in this module and what's expected by the provider.
Under overrides the module asks for `selectors`:

https://github.com/Azure/terraform-azurerm-avm-ptn-alz/blob/e87b448860b92c5066b26ece52f16885e0ea9d27/variables.tf#L90-L98

However the provider wants [`override_selectors`](https://github.com/Azure/terraform-provider-alz/blob/main/docs/data-sources/architecture.md#nested-schema-for-policy_assignments_to_modifypolicy_assignmentsoverrides)

When deploying as is, selectors are ignored and it's instead set as an empty list. When the variable definition is updated to `override_selectors` it works as expected.

Although I've not tested, I suspect `resource_selectors` has the same issue as the provider documentation states it should be `resource_selector_selectors`

**Comment by matt-FFFFFF** [comment]
Hi @JWilkinsonMB thank for raising this. Good catch

**Comment by JWilkinsonMB** [comment]
@matt-FFFFFF - I tried using the fix in https://github.com/Azure/terraform-azurerm-avm-ptn-alz/pull/130, unfortunately it fails on apply. Suspect the issue lies in the provider rather than here, but if I set a not_in value, the `azapi_resource` is set with both in & notIn which is rejected by Azure.

`resource_selector` example below, but it also happens with `overrides`

```HCL
Audit-ResourceRGLocation = {
          resource_selectors = [{
            name = "ResourceTypeExclusions"
            resource_selector_selectors = [{
              kind = "resourceType"
              not_in = [
                "microsoft.network/networkwatchers",
                "microsoft.network/virtualhubs"
              ]
            }]
          }]
        }
```

```HCL
# module.alz.module.alz_global.azapi_resource.policy_assignments["global/Audit-ResourceRGLocation"] will be updated in-place
  ~ resource "azapi_resource" "policy_assignments" {
      ~ body                             = {
          ~ properties = {
              ~ resourceSelectors     = null -> [
                  + {
                      + name      = "ResourceTypeExclusions"
                      + selectors = [
                          + {
                              + in    = []
                              + kind  = "resourceType"
                              + notIn = [
                                  + "microsoft.network/networkwatchers",
                                  + "microsoft.network/virtualhubs",
                                ]
                            },
                        ]
                    },
                ]
                # (9 unchanged attributes hidden)
            }
        }
    }
```

```
│ Error: Failed to create/update resource
│
│   with module.alz.module.alz_global.azapi_resource.policy_assignments["global/Audit-ResourceRGLocation"],
│   on .terraform\modules\alz.alz_global\main.policy_assignments.tf line 1, in resource "azapi_resource" "policy_assignments":
│    1: resource "azapi_resource" "policy_assignments" {
│
│ creating/updating Resource: (ResourceId "/providers/Microsoft.Management/managementGroups/global/providers/Microsoft.Authorization/policyAssignments/Audit-ResourceRGLocation" /   
│ Api Version "2024-04-01"): PUT
│ https://management.azure.com/providers/Microsoft.Management/managementGroups/global/providers/Microsoft.Authorization/policyAssignments/Audit-ResourceRGLocation
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidRequestContent
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidRequestContent",
│     "message": "The request content was invalid and could not be deserialized: 'Invalid operator. Please use only one of the allowed operators: 'in', 'notIn'.'."
│   }
│ }
│ --------------------------------------------------------------------------------
│
```

**Comment by matt-FFFFFF** [comment]
Thanks @JWilkinsonMB, another excellent find - have raised the above to track!

**Comment by JWilkinsonMB** [comment]
Tested with [v0.16.0](https://github.com/Azure/terraform-provider-alz/releases/tag/v0.16.0) of the provider and it's working now, thanks!
