### ISSUE TITLE
[AVM Module Issue]: migrate from https://github.com/Azure/terraform-azurerm-caf-enterprise-scale to  terraform-azurerm-avm-ptn-alz

### ISSUE THREAD

**Issue by MarcelHeek** [Azure/terraform-azurerm-avm-ptn-alz#136]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.9.0-beta2

### Description

Hi,

I am very much interested in using this module, but I am afraid that I fail to see how I can properly use this pattern module to migrate multiple tenant environments where already many workload deployments are done.  The base ALZ structure (Root-MG, Decommissioned, Landingzones, Platform, etc + level 2 MG's) were deployed using the https://github.com/Azure/terraform-azurerm-caf-enterprise-scale method. 

All I could find was that this AVM pattern module could be used to do a pristine ALZ deployment and existing child MG's/subscriptions should be moved from old MG structure to new MG structure. That is not the use case I had in mind. 

The thoughts I had prior to diving a little into the module that I could reference existing structure, with e.g. using data object to get the specific level0/level1/level2 MG's and control policy/role definitions/assignments and add custom definitions/assignments/roles/overrides etc. the same we we now have using the terraform-azurerm-caf-enterprise-scale module. Now it feels like I would have to revert to 

Sure I can understand that the scope of this pattern module includes the ALZ MG structure/levels. But adopting this would benefit greatly from flexibility. 

You state in the latest v6.1.0 release of the terraform-azurerm-caf-enterprise-scale module that once the AVM module is GA ready you will still support this module, but for how long is my main concern.

Hope you can shed some light on this matter 😜

**Comment by matt-FFFFFF** [comment]
Hi Marcel!

We do plan on releasing documentation for the ALZ + AVM module collection, along with migration guidance. This is the reason we are not shouting about this module yet 😉 

As you know, migrating any Terraform state is difficult - especially so across providers! To that end we recommend re-deploying the MG hierarchy and moving over the subscriptions. This is a non-disruptive operation although does require you do have unique MG names.

For key resources such as management and connectivity, we will work on migration tooling but do not have any timescales to share at the moment.

`caf-enterprise-scale` remains fully supported, we plan to share more on this in the coming weeks.

**Comment by matt-FFFFFF** [comment]
#RR

**Comment by MarcelHeek** [comment]
Hi @matt-FFFFFF,

Thanks for your quick response. Really appreciated. I will discuss your response with the team and we will probably end up to keep using the terraform-azurerm-caf-enterprise-scale module but wrap that in a new workflow as it is now wrapped in the Rover / CAF supermodule / caf-terraform-landingzones/caf_solution/add-ons/caf_eslz method (no other way to describe this properly, haha). Which we are in the process of abandoning.

Thanks for keeping up the support for the ALZ module and I will monitor the progress/release of the AVM pattern closely to see if and when moving over is feasible.

**Comment by sriquen** [comment]
@matt-FFFFFF, where could we find the annoucements aroung `caf-enterprise-scale` module?
This sentence `caf-enterprise-scale remains fully supported, we plan to share more on this in the coming weeks.` let me think that something important is coming up, and as we are starting setting up landing zones using enterprise scale architecture, we are interested to learn more about these existing modules.
