### ISSUE TITLE
[AVM Module Issue]: Feature Request: output the mapping set for policy assignment id to policy definition reference ids

### ISSUE THREAD

**Issue by VeronicaSea** [Azure/terraform-azurerm-avm-ptn-alz#137]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Basically, we would like to create the remediation for each assignment, but it requires policy_definition_reference_id. Therefore, would like this [terraform-azurerm-avm-ptn-alz](https://github.com/Azure/terraform-azurerm-avm-ptn-alz) module to output the mapping set for policy_assignment_id to policy_definition_reference_id.
 
resource "azurerm_management_group_policy_remediation" "policy_remediation" {
  name                           = 
  management_group_id            = 
  policy_assignment_id           = 
  policy_definition_reference_id = []
}

**Comment by matt-FFFFFF** [comment]
Hi @VeronicaSea 

Please can you give an example of the data structure you need?

I will then create outputs to suit.

Thanks

**Comment by VeronicaSea** [comment]
@matt-FFFFFF Thank you so much! I would like to have the output data set structure for one object with 2 properties:
{ 
  management_group_id (string),
  policy_role_assignment_resource_id (string),
  policy_definition_reference_id (optional, string)
}

For the argument reference, you can get more detail from here:

[management_group_id](https://registry.terraform.io/providers/hashicorp/azurerm/4.7.0/docs/resources/management_group_policy_remediation#management_group_id) - (Required) The Management Group ID at which the Policy Remediation should be applied. Changing this forces a new resource to be created.

[policy_assignment_id](https://registry.terraform.io/providers/hashicorp/azurerm/4.7.0/docs/resources/management_group_policy_remediation#policy_assignment_id) - (Required) The ID of the Policy Assignment that should be remediated.

[policy_definition_reference_id](https://registry.terraform.io/providers/hashicorp/azurerm/4.7.0/docs/resources/management_group_policy_remediation#policy_definition_reference_id) - (Optional) The unique ID for the policy definition reference within the policy set definition that should be remediated. Required when the policy assignment being remediated assigns a policy set definition.

**Comment by matt-FFFFFF** [comment]
Hi @VeronicaSea 

I can create a list of objects with the above schema. I'd like to ask how you will be creating the remediation task? Do you really want to create one for each assignment and pdref?

**Comment by matt-FFFFFF** [comment]
After consideration we have decided not to implement this feature as it would not serve the intended use case. See internal email.
