### ISSUE TITLE
[AVM Module Issue]:  Error creating custom architecture definitions

### ISSUE THREAD

**Issue by ashley-kainos** [Azure/terraform-azurerm-avm-ptn-alz#142]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.9.2

### Description

On copying the template Arciture definitions example we get an error. We copied the code from the example and when we run a terraform plan we get the following error:

╷
│ Error: architectureDataSource.Read() Error creating architecture custom
│
│   with module.alz_architecture.data.alz_architecture.this,
│   on .terraform\modules\alz_architecture\main.tf line 1, in data "alz_architecture" "this":
│    1: data "alz_architecture" "this" {
│
│ Hierarchy.FromArchitecture: error getting architecture `custom`

**Comment by matt-FFFFFF** [comment]
Hi, in this example we are showing that you can use templating to create the  architecture definition file.

It is created by a separate Terraform root module. You need to run tf apply in the sub directory first to create the file and then run tf apply in the example.

**Comment by matt-FFFFFF** [comment]
#RR
