### ISSUE TITLE
[AVM Module Issue]: Policy Assignment failing when referencing a Policy Set

### ISSUE THREAD

**Issue by ryan-royals** [Azure/terraform-azurerm-avm-ptn-alz#150]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.10.0

### Description

>[!NOTE]
>This may be more related to the `ALZ` provider itself, but this is the best way I have to surface that issue.

```mermaid
flowchart LR
subgraph archetypes
    root_archetype
    platform_archetype
end
subgraph management_groups
    root_mg
    platform_mg
end

root_archetype --> root_mg
platform_archetype --> platform_mg
root_mg --parent_too-->platform_mg
enforce_mandatory_tags --policy_set_definitions_to_add--> root_archetype
enforce_mandatory_tags --policy_assignments_to_add--> platform_archetype
```
When applying a Policy Assignment to a child Archetype, if the Policy is a Policy Set it fails stating `policy assignment `policy-set-name` does not exist in the library`, even though the Policy Assignment at the Parent MG works without issue.
This is following the same pattern found in the `platform/azure`, library, which does work correctly.

## To Reproduce

**[Repo to reproduce bug](https://github.com/ryan-royals/avm-ptn-alz--policy-bug)**

1. Clone repo
2. Init and Apply. 
    - It will fail stating the `Enforce-Mandatory-Tags` policy is not in the library
4. Comment / Delete the `policies_assignments_to_add` on line 5 in `./alz-library/archetype_overrides/platform.alzarchetype_override.json`
5. Apply
    - This will work, and if you check the Policy Definitions in the Azure portal under Root, the `Enforce-Mandatory-Tags` has successfully been defined.

**Comment by matt-FFFFFF** [comment]
Hi @ryan-royals 

Thanks for providing such a clear repo for your issue!

Please can you try creating a file called 

`Enforce-Mandatory-Tags.alz_policy_assignment.json` in your custom library?

You can copy an existing assignment file for this. We need this file to understand which definition to assign and also to get the identity config.

Let me know if this solves the issue!

**Comment by matt-FFFFFF** [comment]
#RR

**Comment by ryan-royals** [comment]
Thanks!
That has caught it. Updated my Repo above to show the fix.

Is there any documentation on what fields are updated by the provider? It seems to be doing some magic on the `policyDefinitionID`, `scope`, and looks like some strings like `${default_location}` and `{enforcementMode}`?

**Comment by matt-FFFFFF** [comment]
Hey.. we document things here:

https://azure.github.io/Azure-Landing-Zones-Library/assets/

If it's not clear or needs updating then please raise an issue!

#RR
