### ISSUE TITLE
[AVM Module Issue]: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by igor-janevski-pbi** [Azure/terraform-azurerm-avm-ptn-alz#152]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

Provider produced inconsistent final plan

### Description

We can't fix below error while using your module:

`Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.alz_archetype_management.time_sleep.before_policy_role_assignments[0]
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/time" produced an invalid new value for
│ .triggers["policy_assignments"]: was
│ cty.StringVal("4fe2692a0e8c972d291e86f9b6be434e6bd5393e5afa6d0ef96fe3961f23f456"),
│ but now
│ cty.StringVal("48b29d1c7f5346c7f8ded2978c0482dd06f57dfa25f4dd89ef6e7593f27cc081").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
`

Any hint would be helpful.

**Comment by matt-FFFFFF** [comment]
Hi there! Thanks for logging this. Can you post your config please?

**Comment by matt-FFFFFF** [comment]
#RR

**Comment by igor-janevski-pbi** [comment]
```
terraform {
  required_version = ">= 1.7.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.96.0"
    }
    alz = {
      source  = "azure/alz"
      version = "< 0.12.0"
    }
  }
}

provider "alz" {
  lib_urls = [
    "./azlib_2024_03_00"
  ]
}

module "alz_management_resources" {
  source                       = "git::https://github.com/Azure/terraform-azurerm-avm-ptn-alz-management?ref=v0.2.0"
  resource_group_name          = "xxxxx-rg"
  location                     = var.location_americas_long
  automation_account_name      = "xxxxx-AA01"
  log_analytics_workspace_name = "xxxxx-LOG01"
  tags                         = var.custom_tags
}

# This allows us to get the tenant id
data "azurerm_client_config" "current" {}

module "alz_archetype_root" {
  source                             = "git::https://github.com/Azure/terraform-azurerm-avm-ptn-alz?ref=v0.6.0"
  id                                 = "${lower(var.client_code)}-alz"
  display_name                       = "xxxxx"
  parent_resource_id                 = "/providers/Microsoft.Management/managementGroups/48073bb3-f36f-4017-a957-f5804c37edcf"
  base_archetype                     = "root"
  default_location                   = var.location_americas_long
  default_log_analytics_workspace_id = module.alz_management_resources.log_analytics_workspace.id
}

module "alz_archetype_platform" {
  source             = "git::https://github.com/Azure/terraform-azurerm-avm-ptn-alz?ref=v0.6.0"
  id                 = "${lower(var.client_code)}-platform"
  display_name       = "Platform"
  parent_resource_id = module.alz_archetype_root.management_group_resource_id
  base_archetype     = "platform"
  default_location   = var.location_americas_long
}
```

**Comment by matt-FFFFFF** [comment]
Hi this is quite an old version, have you considered upgrading?

**Comment by matt-FFFFFF** [comment]
#RR

**Comment by igor-janevski-pbi** [comment]
We considered and tried, it's not a very straight-forward process. Half of the properties are gone/renamed, it wants to re-create everything on the latest version.

**Comment by matt-FFFFFF** [comment]
Hi,

Given that these resources are MG and policy, you can create a new hierarchy by the side of the old one and move subscriptions over.

Now that we are approaching GA, we will have more stability.

At the moment you are using an old version of azapi as well as the module code.

#RR
