### ISSUE TITLE
[AVM Module Issue]: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by sdeguchi** [Azure/terraform-azurerm-avm-ptn-alz#155]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

v0.9.0-beta to v0.10.0

### Description

Want to support users migrating deployments from v0.9.0-beta to v0.10.0. When running the migration, an error message is thrown, but the terraform state is update as expected and subsequent "terraform apply" show no changes in the configuration. Was able to isolate the error using one of the repo examples.

Getting the following error upgrading from module version v0.9.0-beta to v0.10.0:

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.bootstrap.module.management_groups.azapi_resource.policy_role_assignments["be063870-9e84-55e6-b630-dcdbff9933a2"], provider
│ "provider[\"registry.terraform.io/azure/azapi\"]" produced an unexpected new value: .output.properties.updatedOn: was cty.StringVal("2024-11-22T16:55:00.2372370Z"),
│ but now cty.StringVal("2024-11-22T18:04:21.8422725Z").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

Repro steps:
1. Run "terraform apply" using the example: https://github.com/Azure/terraform-azurerm-avm-ptn-alz/blob/v0.9.0-beta/examples/policy-assignment-modification-with-custom-lib/main.tf
 2. Checkout release v0.10.0
 3. Update the local.location from "swedencentral" to "northeurope" (to ensure the terraform configuration matches the previous terraform apply
 4. Make sure you keep the existing terraform.tfstate, run "terraform init --upgrade" and "terraform apply"

**Comment by matt-FFFFFF** [comment]
Hi,

I have reported this to the upstream provider developer.

https://github.com/Azure/terraform-azurerm-avm-ptn-alz/blob/main/main.policy_role_assignments.tf#L42

See this and the line above.

I have tried to ignore the change, but there's a provider level config that you can apply to help fix the issue. See the upstream azapi issue linked in the code.

#RR

**Comment by sdeguchi** [comment]
Confirmed that setting the provider config `disable_default_output = true` resolved the error. Will continue to track the azapi issue. Thanks!
