### ISSUE TITLE
[AVM Module Issue]: Unable to find archetype

### ISSUE THREAD

**Issue by WayneBellows** [Azure/terraform-azurerm-avm-ptn-alz#65]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.6.0

### Description

When you deploy this AVM module the Terraform Plan fails with the below errors. The archetype type in the error changes depending on which archetype you're deploying. I've tested all of them and they all have the same error message. The error below is for the root archetype.

Error: Archetype not found
│ 
│   with module.alz_archetype_root.data.alz_archetype_keys.this,
│   on .terraform/modules/alz_archetype_root/main.tf line 1, in data "alz_archetype_keys" "this":
│    1: data "alz_archetype_keys" "this" {
│ 
│ Unable to find archetype root
╵
╷
│ Error: Archetype not found
│ 
│   with module.alz_archetype_root.data.alz_archetype.this,
│   on .terraform/modules/alz_archetype_root/main.tf line 5, in data "alz_archetype" "this":
│    5: data "alz_archetype" "this" {
│ 
│ Unable to find archetype root

I have been using this AVM module for the last month or so without this error but today this error suddenly started to happen so it looks like something has changed. I haven't changed my code and I'm using the same version. I even tried a new deployment and I had the same error message.

**Comment by ptwisterling** [comment]
I am experiencing the same problem since last sunday. I started to question if it was me or not....

**Comment by matt-FFFFFF** [comment]
Hi,

Apologies - we are making some breaking changes in the provider and alzlib code which caused this issue:

I have pushed another tag to the Library repo. In order to fix the current module please add the following to you root module:

<https://registry.terraform.io/providers/Azure/alz/latest/docs#alz_lib_ref>

```terraform
provider "alz" {
  alz_lib_ref = "platform/alz/2024.03.01-legacy"
}
```

Please not that we will be making more breaking changes before v1.0, as this provider is undergoing active development.

Thanks

**Comment by rick-pb** [comment]
not sure if this actually fixed anything? I've added:
```
provider "alz" {
  #currently a breaking change in the module, this should  be reverted once it's fixed
  alz_lib_ref = "platform/alz/2024.03.01-legacy"
}
```

to my terraform providers in the workspace calling the module but I'm still receiving the following error:
│ Error: Archetype not found
│ 
│   with module.alz_archetype_root.data.alz_archetype_keys.this,
│   on .terraform/modules/alz_archetype_root/main.tf line 1, in data "alz_archetype_keys" "this":
│    1: data "alz_archetype_keys" "this" {
│ 
│ Unable to find archetype root

I can see the root definition created under the .azlib/0 folder in my workspace locally.

**Comment by matt-FFFFFF** [comment]
See this workaround:

https://github.com/Azure/Azure-Landing-Zones-Library/issues/12#issuecomment-2200731543
